config/routes.rb
Rails.application.routes.draw do
  resources :trees
  get 'home/index'
  get 'home/pricing'
  get "up" => "rails/health#show", as: :rails_health_check
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  root "home#index"
  devise_scope :user do
    #get '/users', to: 'devise/registrations#new'
    #get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tree.rb
class Tree < ApplicationRecord
    
    validates :instagram, presence: true, format: { with: /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https])}
    \z/,
    message: 'Invalid URL format' }

    validates :name, presence: true, length: { minimum: 4, message: 'must be at least 4 characters long'}

    extend FriendlyId 
    friendly_id :name, use: :slugged

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one :tree
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    
    def pricing
    end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]

  # GET /trees or /trees.json
  def index
    @trees = Tree.all
  end

  # GET /trees/1 or /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    if current_user.tree.present?
      @notice = "You already have a tree assigned to you."
      redirect_to current_user.tree
    else
      @tree = Tree.new
    end
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees or /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to tree_url(@tree), notice: "Tree was successfully created." }
        format.json { render :show, status: :created, location: @tree }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1 or /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to tree_url(@tree), notice: "Tree was successfully updated." }
        format.json { render :show, status: :ok, location: @tree }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1 or /trees/1.json
  def destroy
    @tree.destroy

    respond_to do |format|
      format.html { redirect_to trees_url, notice: "Tree was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tree_params
      params.require(:tree).permit(:name, :x, :instagram, :youtube, :user_id, :style)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end
  
  def update_resource(resource, params)
    # Require current password if user is trying to change password.
    return super if params["password"]&.present?

    # Allows user to update registration information without password.
    resource.update_without_password(params.except("current_password"))
    
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/home/index.html.erb
<%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="row">
    <p class ="notice"> <%#= notice %>
    <div class="column column=60">
        <div class="content-container">
            <div class="text-content">
                <h1>Everthing you are. In one, single link in bio.</h1>
                <p>Join 40M+ people using Linktree for their link in bio. One link to help you share everything you create, curate and sell from your Instagram, TikTok, Twitter, YouTube, and othe social media profiles.</p>
                <% if user_signed_in? %>
                    <% if current_user.tree.present? %>
                        <%= link_to "View my tree", current_user.tree, class: "button-1", target: "_blank" %>
                    <% else %>
                        <%= link_to "Create your own Link Tree", new_tree_path, class: "button-1", target: "_blank" %>
                    <% end %>
                <% else %>
                    <%= link_to "Create your own Link Tree", new_user_registration_path, class: "button-1", target: "_blank" %>
                <% end %>
            </div>
        </div>
    </div> 

</div>   

app/views/home/pricing.html.erb
<%= stylesheet_link_tag "pricing" %>
<div id="pricing-table" class="clear">
    <div class="plan">
        <h3>Enterprise<span>$59</span></h3>
        <a class="signup" href="">Sign up</a>         
        <ul>
            <li><b>10GB</b> Disk Space</li>
            <li><b>100GB</b> Monthly Bandwidth</li>
            <li><b>20</b> Email Accounts</li>
			<li><b>Unlimited</b> subdomains</li>			
        </ul> 
    </div>
    <div class="plan" id="most-popular">
        <h3>Professional<span>$29</span></h3>
        <a class="signup" href="">Sign up</a>        
        <ul>
            <li><b>5GB</b> Disk Space</li>
            <li><b>50GB</b> Monthly Bandwidth</li>
            <li><b>10</b> Email Accounts</li>
			<li><b>Unlimited</b> subdomains</li>			
        </ul>    
    </div>
    <div class="plan">
        <h3>Standard<span>$17</span></h3>
		<a class="signup" href="">Sign up</a>
        <ul>
            <li><b>3GB</b> Disk Space</li>
            <li><b>25GB</b> Monthly Bandwidth</li>
            <li><b>5</b> Email Accounts</li>
			<li><b>Unlimited</b> subdomains</li>			
        </ul>
    </div>
    <div class="plan">
        <h3>Basic<span>$9</span></h3>
        <a class="signup" href="">Sign up</a>		
        <ul>
            <li><b>1GB</b> Disk Space</li>
            <li><b>10GB</b> Monthly Bandwidth</li>
            <li><b>2</b> Email Accounts</li>
			<li><b>Unlimited</b> subdomains</li>			
        </ul>
    </div> 	
</div>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "navbar" %>
<header>
<div class="navbar">
    <div class="navbar-brand">
     <%= link_to image_tag("tree.png", alt: "Logo", style: "width: 40px;"), home_index_path %>   
    </div>

  <div class="navbar-links">
            <%= link_to "Pricing", home_pricing_path, class:"nav-link" %>
    <% if user_signed_in? %>
        <div class="navbar-user">
            <%= link_to "My account", edit_user_registration_path, class: "nav-link" %>
        <%= link_to "Sign out", destroy_user_session_path, class:"nav-link", style:"border:none;" %>        
        </div>
    <% else %>
        <div class="navbar-auth">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
            <%= link_to "Pricing", home_pricing_path, class: "nav-link" %>
        </div>
    <% end %>
  </div>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linktreeclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/trees/_form.html.erb
<%= form_with(model: tree) do |form| %>
  <% if tree.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
        <% tree.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :x, style: "display: block" %>
    <%= form.text_field :x %>
  </div>

  <div>
    <%= form.label :instagram, style: "display: block" %>
    <%= form.text_field :instagram %>
  </div>

  <div>
    <%= form.label :youtube, style: "display: block" %>
    <%= form.text_field :youtube %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: none" %>
    <%= form.number_field :user_id, value: current_user.id, style: "display: none" %>
  </div>

  <div>
    <%= form.label :style, style: "display: none" %>
    <%= form.text_field :style, style: "display: none" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trees/_tree.html.erb
<div id="<%= dom_id tree %>">
  <p>
    <strong>Name:</strong>
    <%= tree.name %>
  </p>

  <p>
    <strong>X:</strong>
    <%= tree.x %>
  </p>

  <p>
    <strong>Instagram:</strong>
    <%= tree.instagram %>
  </p>

  <p>
    <strong>Youtube:</strong>
    <%= tree.youtube %>
  </p>

</div>

app/views/trees/edit.html.erb
<h1>Editing tree</h1>

<%= render "form", tree: @tree %>

<br>

<div>
  <%= link_to "Show this tree", @tree %> |
  <%= link_to "Back to trees", trees_path %>
</div>

app/views/trees/index.html.erb
<%= stylesheet_link_tag "trees" %>
<p style="color: green"><%= notice %></p>

<div class="container">

<% if user_signed_in?%>

  <%# if current_user.tree.present? %>
 
 <%#= link_to "View my tree", current_user.tree, class: "button-1", target: "_blank" %>
  <%# else %>

  <%= link_to "Create your own Link Tree", new_tree_path, class: "button-1", target: "_blank" %>
  <%# end %>







<% else %>
<%= link_to "Create your own Link Tree", new_user_registration_path, class:"button-1", target:"_blank" %>

<% end %>

</div>

app/views/trees/new.html.erb
<h1>New tree</h1>

<%= render "form", tree: @tree %>

<br>

<div>
  <%= link_to "Back to trees", trees_path %>
</div>

app/views/trees/show.html.erb
<%= stylesheet_link_tag "trees" %>
<p style="color: green"><%= notice %></p>

<div class="container">
<%= render @tree %>

<% if user_signed_in? %>
<% if current_user.id == @tree.user_id %>
<div style="margin-top: 20px;">
  <%= link_to "Edit this tree", edit_tree_path(@tree), class:"button-1" %>
  <%#= link_to "Back to trees", trees_path %>

  <%= button_to "Destroy this tree", @tree, method: :delete, class:"button-1", style:"margin-top: 20px;" %>
</div>
<% end %>
<% end %>
</div>